### ISSUE TITLE
Bug when Depot contains Locked Shares

### ISSUE THREAD

**Issue by sebhaub** [Michael-Beutling/equateplus-moneymoney#3]
Hi there,

i noticed a bug when the account contains shares which are locked until a specific date.
Taking a quick look in the servers response it seems that these are not marked with `AVAIL_QTY` but with `LOCKED_QTY`. Due to this, refreshing the accounts fails with the failure that AVAIL_QTY is not found in the dictionary.

Is it possible to add a switch to handle this case?

How can i help in resolving this?

Thanks for the nice work so far.

Cheers.

**Comment by Michael-Beutling** [comment]
please check the version from branch issue3.
Q: Is the correct amount of shares reported?

**Comment by sebhaub** [comment]
Hey,

thanks for the fast response. Looks very good. With this version it seems to fetch all positions correctly!
