### ISSUE TITLE
The plugin stopped working since October 27th

### ISSUE THREAD

**Issue by Tionit** [Michael-Beutling/equateplus-moneymoney#4]
The EquatePlus extension used to work for me, but since the end of October I can no longer update my account. Web access is still possible with unchanged credentials.

Tested with the extension from https://moneymoney-app.com/extensions/

Is the problem already known? What can I do?

**Comment by Michael-Beutling** [comment]
Can you test the latest version from GitHub?

**Comment by Michael-Beutling** [comment]
The new version is now signed under 
[https://moneymoney-app.com/extensions/EquatePlus.lua](url)
